### ISSUE TITLE
Anti-Spy measures

### ISSUE THREAD

**Issue by dedmen** [blackhandcommando/openrabhc#13]
Allies have Spies. Soviets have Anti-Spy dogs.
This works pretty well if you play Soviet vs Allies.
But if you play Allies vs Allies you have Spies on both sides. But nothing against spies. Besides watching every single of your soldiers very closely.

IMO Allies should also have access to dogs.

**Comment by blackhandcommando** [comment]
Thought about this a while. Came to the conclussion its not harming gameplay in metastyle, since dogs are really rarely used, so why not give some spy defense. Lets implement it in the next update.

**Comment by blackhandcommando** [comment]
Fixed with e7d69644f8c3130530e97f9030cd7c25a7512be3
