### ISSUE TITLE
Merge changes from offical ra into rabhc

### ISSUE THREAD

**Issue by dedmen** [blackhandcommando/openrabhc#3]
Since `rabhc` split from `ra` to go it's own route we also need to integrate atleast some of the fixes done on the offical `ra` mod.
See `ra` history here:
https://github.com/OpenRA/OpenRA/commits/bleed/mods/ra

Especially 
- https://github.com/OpenRA/OpenRA/pull/13031
- https://github.com/OpenRA/OpenRA/commit/d2a0535442aeef097011ed0571557c4037a09e80
- https://github.com/OpenRA/OpenRA/commit/785e20e0f31534eeb413c7d586645ee824892a6c (Probably not that important as rabhc is mostly played on faster anyway)
- https://github.com/OpenRA/OpenRA/pull/12970 (This will change balance a bit.)
- https://github.com/OpenRA/OpenRA/pull/12942 (Maps Added/removed)
- https://github.com/OpenRA/OpenRA/pull/12933 (Maps Added/removed)

**Comment by blackhandcommando** [comment]
I think at this point we need to make a decision for future adaption of official builds.

There is no problem to merge the changes between playtest/stable version, but it will be a regular job to check for (important) changes. Im not sure if we should pick up all/some merges or wait till the next playtest/stable version and merge our changes into it.

Someone got an opinion on that one?

**Comment by dedmen** [comment]
Waiting to the next playtest if ofcause easier. But we would still need to compare all the files and merge their changes into ours. I'd say it would be easier to work of these alread done commits as they show us exactly what line has changed where. We basically already have the diff's and don't need to make them ourselves at the next playtest.

**Comment by dedmen** [comment]
So the new Playtest is now released. https://github.com/OpenRA/OpenRA/wiki/Changelog#red-alert Here is a list of stuff that was changed. That we may merge into rabhc.

**Comment by dedmen** [comment]
So as I've heard we will do a full merge between newest playtest and our changes? I can do that if you want.
according to  https://github.com/OpenRA/OpenRA/wiki/Changelog#red-alert that's only 5 things to be merged

https://github.com/OpenRA/OpenRA/commits/master/mods/ra everything since 31 Mar.

**Comment by dedmen** [comment]
This is solved with #10
